// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oifzicxbxzxlzbttekua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pZnppY3hieHp4bHpidHRla3VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5Mzk0MzYsImV4cCI6MjA3MzUxNTQzNn0.k6ww5QPjCCXg5edvkE6C_H6s8SY3dtud1IOMlVHNVoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});